#포트번호 설정
server:
  port: 8090


uploadPath: C:/Users/home/Desktop/coding/springboot/workspace/Trip/images/ # 실제 이미지를 저장할 로컬 컴퓨터의 폴더 경로
spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  web:
    resources:
      static-locations: classpath:/static/, file:${uploadPath} # 외부 경로를 정적 리소스로 추가




  #Mysql설정
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: travel
    password: 1234
